apiVersion: v1
kind: Service
metadata:
  name: api-service-ms-service
  namespace: api-service-ms-namespace
spec:
  selector:
    app: api-deployment
  ports:
    - protocol: "TCP"
      port: 9198
      targetPort: 9198
  type: NodePort